### ISSUE TITLE
Feature request：增加 markdown 链接

### ISSUE THREAD

**Issue by happyokay** [cryptoli/lite-telegram-image-bot#12]
1. 添加图片，机器人返回链接时，增加一个 markdown 链接
2. 最好链接可以是那种点击就复制，而不是在浏览器打开的格式

**Comment by happyokay** [comment]
比如 BotFather 里建立机器人，它给出的 API 文本，就是那种可以点击就复制的格式

**Comment by happyokay** [comment]
<img width="452" alt="SCR-20240921-sjtj" src="https://github.com/user-attachments/assets/7b9aa122-063b-4020-9594-ba36a12d045f">

**Comment by cryptoli** [comment]
已支持直接复制直链及markdown格式链接

**Comment by happyokay** [comment]
谢谢！
